[platformio]
default_envs = daniel
 ;default_envs = henryk


[tft]
;inversion = -D TFT_INVERSION_ON  ; IPS used
 inversion = -D TFT_INVERSION_OFF ; Normal display

[env:base]
platform = espressif32@^6.12.0
platform_packages =
  tool-esptoolpy@1.40501.0

board = esp32dev
framework = arduino
upload_speed = 921600      ; try 460800 or 115200 if uploads get flaky
monitor_speed = 115200     ; this is ONLY for the serial monitor
board_build.filesystem = littlefs
board_build.partitions = default.csv






build_flags =
  	-Wl,-Map,firmware.map
  	-Wl,--cref
	-D USER_SETUP_LOADED
	-D ILI9488_DRIVER
	-D LOAD_GLCD=1     ; 8x6 basic fixed-width font (fastest, always available)
	-D LOAD_FONT2      ; Small 16-pixel high sans serif font
	-D LOAD_FONT4      ; Medium 26-pixel high sans serif bold font
	-D LOAD_GFXFF      ; Enable access to FreeFonts (stored in SPIFFS/PROGMEM)

	-D SPI_FREQUENCY=27000000
	-D SPI_TOUCH_FREQUENCY=2500000
	-D SPI_READ_FREQUENCY=16000000
	${tft.inversion}

[env:daniel]
extends = env:base
build_flags =
	${env:base.build_flags}
	; Panel QTH (home location)
	-D HOME_LAT_DEG_CFG=46.0f
	-D HOME_LON_DEG_CFG=6.0f
	; TFT display pins
	-D TFT_CS=15
	-D TFT_RST=2
	-D TFT_DC=5
	-D TFT_MOSI=23
	-D TFT_SCLK=18
	-D TFT_BLP=4
	-D TOUCH_CS=17
	-D TFT_MISO=19
	; Encoder pins
	-D PIN_ENC_DT=32
	-D PIN_ENC_CLK=33
	-D PIN_ENC_SW=25
	; HT9200A pins
	-D PIN_DIN=17
	-D PIN_CLK=16
	-D PIN_CS=27
	; Button pins
	-D PIN_PBL=35
	-D PIN_PBR=34
	; SDR_TX relay pin
	-D PIN_REL_SDR_TRX=13
	; I2C pins
	-D PIN_SDA=21
	-D PIN_SCL=22

[env:henryk]
extends = env:base
build_flags =
	${env:base.build_flags}
	; Panel QTH (home location)
	-D HOME_LAT_DEG_CFG=46.0f
	-D HOME_LON_DEG_CFG=6.0f
	; TFT display pins
	-D TFT_CS=23
	-D TFT_RST=19
	-D TFT_DC=18
	-D TFT_MOSI=05
	-D TFT_SCLK=15
	-D TFT_BLP=17
	-D TOUCH_CS=16
	-D TFT_MISO=4
	; Encoder pins
	-D PIN_ENC_DT=32
	-D PIN_ENC_CLK=33
	-D PIN_ENC_SW=25
	; HT9200A pins
	-D PIN_DIN=26
	-D PIN_CLK=27
	-D PIN_CS=14
	; Button pins
	-D PIN_PBL=35
	-D PIN_PBR=34
	; SDR_TX relay pin
	-D PIN_REL_SDR_TRX=13
	; I2C pins
	-D PIN_SDA=21
	-D PIN_SCL=22

