#!/usr/bin/env python3
"""
encode.py

Reads elegant.html from the current folder, gzip-compresses it, and writes
a new elop.cpp file containing a uint8_t PROGMEM array called ELEGANT_HTML.

Usage:
    python encode.py
"""

import gzip

INPUT_HTML = "elegant.html"
OUTPUT_CPP = "elop.cpp"
VAR_NAME = "ELEGANT_HTML"


def to_c_array(data, var_name=VAR_NAME):
    """Convert bytes into a nicely formatted C uint8_t PROGMEM array."""
    lines = []
    lines.append(f"const uint8_t {var_name}[{len(data)}] PROGMEM = {{")

    line = "    "
    for i, b in enumerate(data):
        line += f"{b},"
        # 16 bytes per line for readability
        if (i + 1) % 16 == 0:
            lines.append(line)
            line = "    "

    if line.strip():
        lines.append(line)

    lines.append("};")
    return "\n".join(lines)


def main():
    print(f"[INFO] Reading HTML from: {INPUT_HTML}")
    with open(INPUT_HTML, "rb") as f:
        raw = f.read()

    print(f"[INFO] HTML size: {len(raw)} bytes")

    compressed = gzip.compress(raw)
    print(f"[INFO] Compressed size: {len(compressed)} bytes")

    array_text = to_c_array(compressed, VAR_NAME)

    cpp_contents = (
        "// Auto-generated by encode.py – do not edit by hand.\n"
        "#include <Arduino.h>\n"
        "#include \"elop.h\"\n\n"
        f"{array_text}\n"
    )

    with open(OUTPUT_CPP, "w", encoding="utf-8") as f:
        f.write(cpp_contents)

    print(f"[OK] Wrote C array '{VAR_NAME}' to: {OUTPUT_CPP}")


if __name__ == "__main__":
    main()
